CONSOLIDATED_TABLE_STRUCTURE = {
    # Format 'sql_col_name': ('sql_datatype', 'horses_consolidated_performances_col', 'race_horse_info_col', 'horse_pps col')
    'source_file':          ('VARCHAR(255)',    'source_file',  'source_file',      'source_file'),
    'track':                ('VARCHAR(255)',    'track',        'track',            'track_code'),
    'date':                 ('DATE',            'date',         'date',             'race_date',),
    'race_num':             ('TINYINT',         'race_num',     'race_num',         'race_num'),
    'distance':             ('INT',             'distance',     None,               'distance'),

    'horse_name':           ('VARCHAR(255)',    'horse_name',   'horse_name',       'horse_name'),
    'horse_id':             ('VARCHAR(255)',    'horse_id',     'horse_id',         None),
    'post_position':        ('TINYINT',         'post_position','post_position',    'post_position'),
    'coupled_entry':        ('VARCHAR(255)',    'coupled_entry','coupled_entry',    None),
    'days_old':             ('INT',             'days_old',     None,               None),
    'state_bred':           ('VARCHAR(255)',    'state_bred',   'state_bred',       None),

    'days_since_last_race': ('INT',             'days_since_last_race', None,       'days_since_last_race'),
    'favorite':             ('INT',             'favorite',     'favorite',         'favorite'),

    'weight':               ('SMALLINT',        'weight',       'weight',           'weight'),


    'dead_heat_finish':     ('TINYINT', 'dead_heat_finish',     'dead_heat_finish', None),

    'position_0':           ('TINYINT', 'position_0',       None, None),
    'position_330':         ('TINYINT', 'position_330',     None, None),
    'position_440':         ('TINYINT', 'position_440',     None, None),
    'position_660':         ('TINYINT', 'position_660',     None, None),
    'position_880':         ('TINYINT', 'position_880',     None, None),
    'position_990':         ('TINYINT', 'position_990',     None, None),
    'position_1100':        ('TINYINT', 'position_1100',    None, None),
    'position_1210':        ('TINYINT', 'position_1210',    None, None),
    'position_1320':        ('TINYINT', 'position_1320',    None, None),
    'position_1430':        ('TINYINT', 'position_1430',    None, None),
    'position_1540':        ('TINYINT', 'position_1540',    None, None),
    'position_1610':        ('TINYINT', 'position_1610',    None, None),
    'position_1650':        ('TINYINT', 'position_1650',    None, None),
    'position_1760':        ('TINYINT', 'position_1760',    None, None),
    'position_1830':        ('TINYINT', 'position_1830',    None, None),
    'position_1870':        ('TINYINT', 'position_1870',    None, None),
    'position_1980':        ('TINYINT', 'position_1980',    None, None),

    'lead_or_beaten_0':     ('FLOAT',    'lead_or_beaten_0',     None, None),
    'lead_or_beaten_330':   ('FLOAT',    'lead_or_beaten_330',   None, None),
    'lead_or_beaten_440':   ('FLOAT',    'lead_or_beaten_440',   None, None),
    'lead_or_beaten_660':   ('FLOAT',    'lead_or_beaten_660',   None, None),
    'lead_or_beaten_880':   ('FLOAT',    'lead_or_beaten_880',   None, None),
    'lead_or_beaten_990':   ('FLOAT',    'lead_or_beaten_990',   None, None),
    'lead_or_beaten_1100':  ('FLOAT',    'lead_or_beaten_1100',  None, None),
    'lead_or_beaten_1210':  ('FLOAT',    'lead_or_beaten_1210',  None, None),
    'lead_or_beaten_1320':  ('FLOAT',    'lead_or_beaten_1320',  None, None),
    'lead_or_beaten_1430':  ('FLOAT',    'lead_or_beaten_1430',  None, None),
    'lead_or_beaten_1540':  ('FLOAT',    'lead_or_beaten_1540',  None, None),
    'lead_or_beaten_1610':  ('FLOAT',    'lead_or_beaten_1610',  None, None),
    'lead_or_beaten_1650':  ('FLOAT',    'lead_or_beaten_1650',  None, None),
    'lead_or_beaten_1760':  ('FLOAT',    'lead_or_beaten_1760',  None, None),
    'lead_or_beaten_1830':  ('FLOAT',    'lead_or_beaten_1830',  None, None),
    'lead_or_beaten_1870':  ('FLOAT',    'lead_or_beaten_1870',  None, None),
    'lead_or_beaten_1980':  ('FLOAT',    'lead_or_beaten_1980',  None, None),

    'meds_adjunct_bleeder': ('TINYINT',     'meds_adjunct_bleeder', 'adjunct_bleeder_meds', None),
    'meds_bute':            ('TINYINT',     'meds_bute',            'bute',                 'medication_bute'),
    'meds_lasix':           ('TINYINT',     'meds_lasix',           'lasix',                'medication_lasix'),

    'equip_running_ws':     ('TINYINT',     'equip_running_ws',     'equip_running_ws',         None),
    'equip_screens':        ('TINYINT',     'equip_screens',        'equip_screens',            None),
    'equip_shields':        ('TINYINT',     'equip_shields',        'equip_shields',            None),
    'equip_aluminum_pads':  ('TINYINT',     'equip_aluminum_pads',  'equip_aluminum_pads',      None),
    'equip_blinkers':       ('TINYINT',     'equip_blinkers',       'equip_blinkers',           'blinkers'),
    'equip_mud_calks':      ('TINYINT',     'equip_mud_calks',      'equip_mud_calks',          None),
    'equip_glued_shoes':    ('TINYINT',     'equip_glued_shoes',    'equip_glued_shoes',        None),
    'equip_inner_rims':     ('TINYINT',     'equip_inner_rims',     'equip_inner_rims',         None),
    'equip_front_bandages': ('TINYINT',     'equip_front_bandages', 'equip_front_bandages',     'front_wraps'),
    'equip_goggles':        ('TINYINT',     'equip_goggles',        'equip_goggles',            None),
    'equip_outer_rims':     ('TINYINT',     'equip_outer_rims',     'equip_outer_rims',         None),
    'equip_inserts':        ('TINYINT',     'equip_inserts',        'equip_inserts',            None),
    'equip_aluminum_pad':   ('TINYINT',     'equip_aluminum_pad',   'equip_aluminum_pad',       None),
    'equip_flipping_halter':('TINYINT',     'equip_flipping_halter','equip_flipping_halter',    None),
    'equip_bar_shoes':      ('TINYINT',     'equip_bar_shoes',      'equip_bar_shoes',          None),
    'equip_blocks':         ('TINYINT',     'equip_blocks',         'equip_blocks',             None),
    'equip_no_whip':        ('TINYINT',     'equip_no_whip',        'equip_no_whip',            None),
    'equip_blinkers_off':   ('TINYINT',     'equip_blinkers_off',   'equip_blinkers_off',       None),
    'equip_pads':           ('TINYINT',     'equip_pads',           'equip_pads',               None),
    'equip_nasal_strip_off':('TINYINT',     'equip_nasal_strip_off','equip_nasal_strip_off',    None),
    'equip_bar_shoe':       ('TINYINT',     'equip_bar_shoe',       'equip_bar_shoe',           'bar_shoe'),
    'equip_nasal_strip':    ('TINYINT',     'equip_nasal_strip',    'equip_nasal_strip',        None),
    'equip_turndowns':      ('TINYINT',     'equip_turndowns',      'equip_turndowns',          None),
    'equip_spurs':          ('TINYINT',     'equip_spurs',          'equip_spurs',              None),
    'equip_cheek_piece':    ('TINYINT',     'equip_cheek_piece',    'equip_cheek_piece',        None),
    'equip_queens_plates':  ('TINYINT',     'equip_queens_plates',  'equip_queens_plates',      None),
    'equip_cheek_piece_off':('TINYINT',     'equip_cheek_piece_off','equip_cheek_piece_off',    None),
    'equip_no_shoes':       ('TINYINT',     'equip_no_shoes',       'equip_no_shoes',           None),
    'equip_tongue_tie':     ('TINYINT',     'equip_tongue_tie',     'equip_tongue_tie',         None),

    'jockey_id':            ('INT',             'jockey_id',    'jockey_id',    None),
    'jockey':               ('VARCHAR(255)',    'jockey',       'jockey',       'jockey'),
    'trainer_id':           ('INT',             'trainer_id',   'trainer_id',   None),
    'trainer':              ('VARCHAR(255)',    'trainer',      'trainer_name', 'trainer'),
}